common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
#페이지 요청이 발생하면 가장 먼저 실행되는 파일
"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
#django.contrib에서 admin(관리자페이지)기능을
#미리 만들어 놓음 그래서 우리는 그것을 가져다 씀
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

#pybo기능을 우리가 자체 제작하고
#그 기능을 가져다 씀
#from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls), #admin페이지 요청이 발생하면 admin.site.urls 기능으로 연결하세요!
    #path('pybo/',views.index), #pybo페이지 요청이 발생하면 views.index 기능으로 연결하세요!
    path('pybo/', include('pybo.urls')), #pybo페이지 요청이 발생하면 pybo디렉터리의 urls.py를 참조하겠다!
    path('common/',include('common.urls')),
    path('', base_views.index, name='index'), # '/'에 해당되는 path
]

pybo/urls.py
from django.urls import path
#config의 urls의 깔끔한 작성을 돕는 멀티탭같은 역할


from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    #base_views.py
    path('',base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name = 'detail'),

    #question_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create,name='answer_create'),
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',question_views.question_modify,name='question_modify'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    #answer_views.py
    path('question/delete/<int:question_id>/',question_views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote,
         name='answer_vote'),
]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Question

from django.db.models import Q

def index(request):
    page = request.GET.get('page','1') #페이지
    kw = request.GET.get('kw','') #검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) | #제목검색
            Q(content__icontains=kw) | #내용검색
            Q(answer__content__icontains=kw) | #답변 내용 검색
            Q(author__username__icontains=kw) | #질문 글쓴이 검색
            Q(answer__author__username__icontains=kw) #답변 글쓰닝 검색
        ).distinct()
    paginator = Paginator(question_list,10) #페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page':page, 'kw':kw}
    return render(request, 'pybo/question_list.html',context)

def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    #500error대신 404error을 출력하기 위함
    question = get_object_or_404(Question, pk = question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tagss -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>파이보</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!--기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!--기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{error}}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navebar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aris-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>